version: "3.8"

services:

  frontend:
    build: ./frontend
    image: black-hole-frontend:v0.1
    container_name: frontend
    ports:
      - "9999:80"
    volumes:
      - "./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend

  backend:
    build: .
    image: black-hole-backend:v0.1
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: password
      DB_NAME: black_hole
    ports:
      - "8080:8080"
    volumes:
      - "./backend/storage:/app/storage"
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: black_hole
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql